version: '3.8'
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: rionagasaki
      POSTGRES_PASSWORD: nagari0530
      POSTGRES_DB: to-do-db
    restart: always
    networks:
      - lesson
networks:
  lesson:
